In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("../image/RGB_test.png")
img_gray = cv2.imread("../image/RGB_test.png" , cv2.IMREAD_GRAYSCALE)
print(type(img))

<class 'numpy.ndarray'>


In [3]:
type(img)

numpy.ndarray

In [4]:
img.shape

(225, 225, 3)

In [5]:
def showImage(img) :
    cv2.imshow("xxxx",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    for i in range (1,5):
        cv2.waitKey(1)

In [6]:
print(type(img),img.shape)
b,g,r = cv2.split(img)
print(type(b) , b.shape)
print(type(g) , g.shape)
print(type(r) , r.shape)

<class 'numpy.ndarray'> (225, 225, 3)
<class 'numpy.ndarray'> (225, 225)
<class 'numpy.ndarray'> (225, 225)
<class 'numpy.ndarray'> (225, 225)


In [7]:
img2 = cv2.vconcat([b,g,r])
showImage(img2)

In [8]:
print(img_gray.shape , type(img_gray.shape))
showImage(img_gray)
row , col , n = img.shape

(225, 225) <class 'tuple'>


In [9]:
gray = np.zeros([row,col] , dtype = 'float')
print(gray)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
gray = gray.astype(np.float16)
for i in range(row) :
    for j in range(col) :
        gray[i,j] = 0.1140*img[i,j,0] + 0.5870*img[i,j,1] + 0.2989*img[i,j,2]

In [11]:
gray = gray.astype(np.uint8)

In [ ]:
showImage(gray)

: 